---
version: 2

# It's fine to have dependabot consider more languages than used in the repo.

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: monthly

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      go:
        patterns: ["*"]
    schedule:
      interval: monthly

  - package-ecosystem: "npm"
    directory: "/"
    groups:
      npm:
        patterns: ["*"]
    schedule:
      interval: monthly
