---
# Ref: https://golangci-lint.run/usage/configuration/
linters:
  enable-all: true

  disable:
    # TODO: remove the line and fix the issues
    - depguard
    - err113
    - forbidigo
    - mnd
    - inamedparam
    - ireturn
    - musttag
    - nestif
    - paralleltest
    - predeclared
    - revive
    - wrapcheck
    - wsl

    - cyclop # some functions need refactoring, I'll deal with that later
    - nlreturn # keeps the code concise
    - godox # I like leaving TODOs in the code
    - varnamelen # short variable names are okay
    - testpackage # keep the tests close to the code
    - exhaustruct # it's ok not to specify all the fields in a struct definition

    # deprecated
    - exportloopref

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - bodyclose
        - funlen

    - path: internal/cmd
      linters:
        # using init() is recommended with spf13/cobra
        - gochecknoinits
        # using globals is recommended with spf13/cobra
        - gochecknoglobals

    - path: internal/version
      linters:
        - gochecknoglobals

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule

  revive:
    enable-all-rules: true
    rules:
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T"

  tagliatelle:
    case:
      rules:
        json: snake

  misspell:
    locale: US
    mode: default
