---
# Ref: https://golangci-lint.run/usage/configuration/
linters:
  enable-all: true

  disable:
    # TODO: remove the line and fix the issues
    - cyclop
    - depguard
    - err113
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - mnd
    - inamedparam
    - ireturn
    - lll
    - musttag
    - nestif
    - paralleltest
    - predeclared
    - recvcheck
    - revive
    - whitespace
    - wrapcheck
    - wsl

    - nlreturn # keeps the code concise
    - godox # I like leaving TODOs in the code
    - varnamelen # short variable names are okay
    - testpackage # keep the tests close to the code
    - exhaustruct # it's ok not to specify all the fields in a struct definition

    # deprecated
    - exportloopref

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - bodyclose
        - funlen

linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule

  revive:
    enable-all-rules: true
    rules:
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T"

  tagliatelle:
    case:
      rules:
        json: snake

  misspell:
    locale: US
    mode: default
