# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/gh-not
    env:
      - CGO_ENABLED=0
    ldflags:
      - >
        -s -w -X github.com/nobe4/gh-not/internal/cmd.version=v{{.Version}}
              -X github.com/nobe4/gh-not/internal/cmd.commit={{.Commit}}
              -X github.com/nobe4/gh-not/internal/cmd.date={{.Date}}

archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

release:
  draft: false
