# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
# Local testing: goreleaser --snapshot --clean

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/gh-not
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/nobe4/gh-not/internal/version.tag={{.Tag}}

archives:
  - name_template: "{{ .Os }}-{{ .Arch }}"
    format: binary

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github-native

release:
  draft: false
