#!/usr/bin/env bash

find . -not -path './.git/*' -not -path './dist/*' | \
    entr -c \
    bash -c '
        go test -cover -coverprofile=coverage ./... &&
        go tool cover -html=coverage -o coverage.html
    '
